### ISSUE TITLE
Attach Avi Controller: Fails to add endpoint

### ISSUE THREAD

**Issue by bmarkussen** [avinetworks/avi-vrealize-orchestrator-plugin#126]
### Describe the bug

* After upgrading from o11nplugin-vro-21.1.3.RELEASE.dar to o11nplugin-vro-22.1.2.RELEASE.dar the AVI endpoint is missing in the vRO inventory. 
When running workflow: "Attach Avi Controller" I get error:
ERROR(com.vmware.avi/attachVroClient) Error in (Dynamic Script Module name : attachVroClient#2) java.lang.Exception: Controller with the same IP is already exists: "host.domain.com-admin"

* Troubleshooting: 
Removing and reinstalling o11nplugin-vro-22.1.2.RELEASE.dar
When running workflow: "Attach Avi Controller" I get error:
ERROR(com.vmware.avi/attachVroClient) Error in (Dynamic Script Module name : attachVroClient#2) java.lang.Exception: Controller with the same IP is already exists: "host.domain.com-admin"

AVI 22.1.2 Build 9086
vRO is embedded in vRA:
vRealize Orchestrator 8.10.0.20565372
vRealize Automation 8.10.0.26552 (20566543)

### Reproduction steps

1. Install o11nplugin-vro-22.1.2.RELEASE.dar
2. Run workflow: "Attach Avi Controller"
3. 
...

### Expected behavior

AVI Endpoint should be visible in vRO Inventory 

### Additional context
AVI 22.1.2 Build 9086
vRO is embedded in vRA:
vRealize Orchestrator 8.10.0.20565372
vRealize Automation 8.10.0.26552 (20566543)

**Comment by mkhachane** [comment]
Hi @bmarkussen  Can you please share the logs as well? We are not able to reproduce the issue.

**Comment by bmarkussen** [comment]
I have renamed servernames and useraccount name. vco-server-app.log for node2 is attached.
Any other logfile you need?

[vranode2-vco-server-app.log](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/files/9919235/vranode2-vco-server-app.log)

**Comment by bmarkussen** [comment]
FYI: I have tried to add the o11nplugin-vro-22.1.2.RELEASE.dar to an other environment. 
In that environment there is no error when running "Attach Avi Controller", but the Avi endpoint is not shown in the vRO inventory.  
Running "Attach Avi Controller" a second time gives the error: 
ERROR(com.vmware.avi/attachVroClient) Error in (Dynamic Script Module name : attachVroClient#2) java.lang.Exception: Controller with the same IP is already exists: "host.domain.com-admin"

AVI 22.1.1 Build 9052  (Single node)
vRO is embedded in vRA:
vRealize Orchestrator 8.10.0.20565372 (Single node)
vRealize Automation 8.10.0.26552 (20566543) (Single node)

**Comment by mkhachane** [comment]
Hi @bmarkussen Can you please try to remove the vRO plugin and reinstall it and share the starting logs for the same?

**Comment by bmarkussen** [comment]
Hi @mkhachane 
I have done these steps and attached log files.

1. 8:13CET Uninstall vRO Plugin
2. Waiting for vRO to restart
3. 8:18CET Installing vRO Plugin
4. Waiting for vRO to restart
5. 8:27CET Running "Attach Avi Controller" - Error:

2022-11-03 08:27:56.740 +01:00INFO__item_stack:/item1
2022-11-03 08:27:56.810 +01:00ERROR(com.vmware.avi/attachVroClient) Error in (Dynamic Script Module name : attachVroClient#2) java.lang.Exception: Controller with the same IP is already exists: avi-ctrl1.markussenit.dk-admin
2022-11-03 08:27:56.826 +01:00ERRORWorkflow execution stack:
***
item: 'Attach Avi Controller/item1', state: 'failed', business state: 'null', exception: 'java.lang.Exception: Controller with the same IP is already exists: avi-ctrl1.markussenit.dk-admin (Dynamic Script Module name : attachVroClient#2)'
workflow: 'Attach Avi Controller' (d541c0da-5105-4c9b-b73b-bae90340e31f) 
|  'attribute': name=errorCode type=string value=
		
|  'attribute': name=host type=string value=avi-ctrl1.markussenit.dk
|  'input': name=controller type=string value=avi-ctrl1.markussenit.dk
|  'input': name=username type=string value=admin
|  'input': name=password type=SecureString value=__NULL__
|  'input': name=tenant type=string value=admin
|  'input': name=version type=string value=22.1.1
|  'input': name=token type=SecureString value=__NULL__
|  'input': name=token_based_auth type=boolean value=false
|  'input': name=ignore_warnings type=boolean value=true
|  'no outputs'
*** End of execution stack.


AVI 22.1.1 Build 9052 (Single node)
vRO is embedded in vRA:
vRealize Orchestrator 8.10.0.20565372 (Single node)
vRealize Automation 8.10.0.26552 (20566543) (Single node)


[washed-console-logs-vco-server-app.log](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/files/9926507/washed-console-logs-vco-server-app.log)

[washed-file-logs-vco-server-app.log](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/files/9926509/washed-file-logs-vco-server-app.log)

**Comment by mkhachane** [comment]
Hi @bmarkussen  Can you please try to remove resource endpoint from the vRO instance and try to run Attach Avi Controller Workflow? Below are the steps to remove the endpoint,
1. Navigate to assets tab of the vRO instance and remove the **avi-ctrl1.markussenit.dk-admin** from the resources.
2. Run Attach Avi Controller workflow.

**Comment by bmarkussen** [comment]
Done - Same error. 
I have made screenshot of the steps. see attached pdf file.
[vRO AVI ERROR.pdf](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/files/9938699/vRO.AVI.ERROR.pdf)

**Comment by kskilling** [comment]
I can reproduce simliar behaviour with an environment running vRO 8.10 (embedded instance, single node). When installing vRO plugin release 22.1.2 and running the attach workflow and using the plugin version number of 22.1.2 as the version input parameter value I see the AVI controller added to the inventory in vRO however it does not retrieve the configuration from AVI to expand the object in vRO inventory. If I detach and attach again using the AVI controller version number of 21.1.4 it appears in the vRO inventory and I can expand the controller to see the configuration present within AVI. What is the version input parameter used for that could be causing this behaviour. I can provide access to the lab environment internally to VMware employees for log analysis etc if required.
<img width="1418" alt="Screenshot 2022-11-09 at 14 04 06" src="https://user-images.githubusercontent.com/48841085/200838156-6bf4ed7d-de5d-44a8-90ae-88c4831827ed.png">

Upgraded to the latest controller version 22.1.2 and same behaviour after detaching and attaching again, unable to expand the inventory.

**Comment by bmarkussen** [comment]
Hi @mkhachane
When do you expect to have time to give feedback on this Issue?

**Comment by mkhachane** [comment]
Hi @bmarkussen 
We have fixed this issue, you will get the fix on the vRO plugin version 21.1.6 release.

**Comment by bmarkussen** [comment]
> Hi @bmarkussen We have fixed this issue, you will get the fix on the vRO plugin version 21.1.6 release.

Thanks, @mkhachane
Do you have an ETA for 21.1.6?
Will there be a fix for 22.1.x as well?

**Comment by mkhachane** [comment]
Hi @bmarkussen 
21.1.6 will be around end of this month.
Yes, it will be available for 22.1.x as well.

**Comment by bmarkussen** [comment]
Hi @mkhachane 

I have tested the following:
vRA/vRO 8.10 single node:
vRO Plugin 22.1.2.post1 (22.1.2.1)

Connection to Avi Controller 22.1.2 2p3 (Version parameter set to 22.1.2) is shown in inventory, and Avi object are listed 
Connection to Avi Controller 22.1.1 2p2 (Version parameter set to 22.1.1) is shown in inventory, but Avi objects are not listed.

I will test futher in the comming days.

**Comment by bmarkussen** [comment]
Hi @mkhachane

I'm sorry for the late reply - But unfortunately I still have issues.
@kskilling did you have a chance to test the updated plugin?

---

**_Environment A
vRA/vRO 8.10 single node:
Avi 22.1.2 2p3
vRO Plugin 22.1.2.post1 (22.1.2.1)
AVI Configured Cloud: VMware vCenter/vSphere ESX_**

First issue:
Attaching Avi Controller 22.1.2 2p3 (Version parameter set to 22.1.2) 
Avi endpoint is shown in inventory, but the configured virtual service is not shown:
![image](https://user-images.githubusercontent.com/64780343/208078135-0d58b0ad-1812-4a44-9f64-606ed689cae6.png)

![image](https://user-images.githubusercontent.com/64780343/208078751-80b6c6da-8488-4874-8e71-0e78308ccbcc.png)

Second issue:
Trying to add Virtual Service, the Avi endpoint is shown, but the server_cloud is not shown in the dropdown:
![image](https://user-images.githubusercontent.com/64780343/208079539-9a5d9c5e-8d00-4268-88bc-b94ff1c2cec5.png)

---

---

**_Environment B
vRA/vRO 8.10 3 node cluster:
Avi 22.1.2 2p3
vRO Plugin 22.1.2.post1 (22.1.2.1)
AVI Configured Cloud: NSX-T Cloud_** 

Attaching  Avi Controller 22.1.2 2p3 (Version parameter set to 22.1.2) 
Avi endpoint is shown in inventory and the configured virtual service is shown as expected.

Third issue:
"Create Virtual Service NSX-T LB" fails with error: 

2022-12-16 10:26:37.910 +01:00INFO__item_stack:/item8
2022-12-16 10:26:37.917 +01:00INFOWorkflow ID in action:-> 731515498
2022-12-16 10:26:37.998 +01:00ERROR(com.vmware.avi/finishVroWorkflow) Error in (Dynamic Script Module name : finishVroWorkflow#4) 
{"error": "Tenant 'org.mozilla.javascript.NativeArray@4843d755' does not exist!"}:: Inside Rollback ::null
::null
2022-12-16 10:26:38.010 +01:00ERRORWorkflow execution stack:
"***"
item: 'Create Virtual Service NSX-T LB/item8', state: 'failed', business state: 'null', exception: '
{"error": "Tenant 'org.mozilla.javascript.NativeArray@4843d755' does not exist!"}:: Inside Rollback ::null
::null (Dynamic Script Module name : finishVroWorkflow#4)'
workflow: 'Create Virtual Service NSX-T LB' (6b35104b-2cff-4b2e-91f2-0dfa4cd7f205) 



I hope you will be able to help me.

Thank you,

Brian

**Comment by kskilling** [comment]
@bmarkussen I have now been able to do some basic testing and can confirm I also have issues with the latest release of the plugin. Here are my results:
**Environment configuration**
- vRA with embedded vRO single node 8.10 (Version 8.10.0.26552 (20566543))
- AVI Controller 22.1.2 Build 9086
- Plugin release 22.1.2.post1 (22.1.2.1)
- Single virtual service configured on the AVI controller as a test.

**Steps performed**
1. Detached the existing instance of the AVI controller from vRO using the workflow from the plugin.
2. Attached AVI controller in vRO using the workflow from the plugin.
3. Checked the vRO inventory. vRO Inventory shows the AVI Controller but not the virtual server (same as Brian reported in the previous comment).
4. Ran the Create VS workflow, and the AVI controller instance and the virtual service are not populated in the drop-down input boxes.

![Screenshot 2023-01-12 at 08 56 11](https://user-images.githubusercontent.com/48841085/212022264-930429a8-c0ac-4544-a866-211375301b1e.png)

**Comment by mkhachane** [comment]
We are not able to reproduce the issue on vRO 8.11 single node server. Can you please try with 8.11 vRO single node server?

**Comment by bmarkussen** [comment]
> We are not able to reproduce the issue on vRO 8.11 single node server. Can you please try with 8.11 vRO single node server?

@mkhachane 
I will upgrade my environment and test if the issue is solved. I will get back to you within a few days.

**Comment by bmarkussen** [comment]
Hi @mkhachane 

I have upgraded the environment and get the same errors:

vRA/vRO 8.11.0.20963650 single node:
Avi 22.1.2 2p3 
vRO Plugin 22.1.2.post1 (22.1.2.1)
AVI Configured Cloud: VMware vCenter/vSphere ESX

Issue 1:
Attaching Avi controller is working, but the VS is not shown:
![image](https://user-images.githubusercontent.com/64780343/214593785-804de3fd-2d23-448a-90de-dad81771bdae.png)

![image](https://user-images.githubusercontent.com/64780343/214594236-71a2c145-0bf1-44b1-aa72-8e84d6ece6a4.png)

Issue 2:
When running workflow VS Create the server_cloud is not published:
![image](https://user-images.githubusercontent.com/64780343/214596309-69248e65-84ff-49bb-8160-ac0d5ae5a613.png)

**Comment by kskilling** [comment]
I'm trying to get my vRO lab upgraded to 8.11 to complete testing to see if I still get issues. I will update this issue once I have results.

**Comment by kskilling** [comment]
I have upgraded my lab to 8.11 (single node, latest AVI plugin version) and have the same behaviour as @bmarkussen is reporting. AVI controller appears in inventory after running the attach workflow but VS isn't shown. When running workflow VS Create the server_cloud is not published.
In my lab, the VS in AVI is unhealthy as it is just an empty instance created for testing, and does not have the associated networks available to report as healthy.
<img width="1313" alt="Create VS Workflow" src="https://user-images.githubusercontent.com/48841085/215516374-5df0ace7-b745-4b2c-9fa1-a2cc4eedc38f.png">
<img width="450" alt="vRO Inventory" src="https://user-images.githubusercontent.com/48841085/215516380-4591f9cd-fc11-4e0e-a869-ac3b6b569701.png">
@mkhachane My lab is accessible to any VMware employee if you would like to reproduce the issue for investigation.

**Comment by mkhachane** [comment]
> Create Virtual Service NSX-T LB" fails with error:

For Above issue, there is a workaround. It will be fixed in upcoming release.
Add following line after line number 2 in createHealthMonitorObj action as per the screenshot below,
`Tenant = workflowRuntime.getAviVroClient().cred.tenant;`

<img width="1746" alt="Screenshot 2023-02-02 at 7 45 49 PM" src="https://user-images.githubusercontent.com/36229179/216350175-f56b3a38-fc15-4031-a672-e274e9a14181.png">

**Comment by bmarkussen** [comment]
Hi @mkhachane

Thank for the workaround for "Create Virtual Service NSX-T LB" fails with error"
  "Tenant = workflowRuntime.getAviVroClient().cred.tenant;" fixes the NSX-T issue.

/Brian

**Comment by bmarkussen** [comment]
Hi @mkhachane 
Then we have the other issue that both @kskilling and I see:
When using vCenter Cloud (No NSX-T configured) 
When running workflow "VS Create" the server_cloud is not published.
![image](https://user-images.githubusercontent.com/64780343/216919382-a7e272a9-dffc-479a-9fea-9ab6582c0f7a.png)

Do you have a fix for this as well?

/Brian

**Comment by bmarkussen** [comment]
Update on this issue:
Several version upgrades since initial creation of Issue 126:

**Environment B**
vRA/vRO 8.10 3 node cluster:
Avi 22.1.3
vRO Plugin 22.1.3
AVI Configured Cloud: NSX-T Cloud (NSX-T 3.2.1.2)
"Create Virtual Service NSX-T LB" is working now.
**I will close Issue 126.**


**Environment A**
vRA/vRO 8.11 single node:
Avi 22.1.3
vRO Plugin 22.1.3
AVI Configured Cloud: VMware vCenter/vSphere ESX

First issue:
Attaching Avi Controller 22.1.3 (Version parameter set to 22.1.3)
Avi endpoint is shown in inventory, but the configured virtual service is not shown:

Second issue:
Trying to "Create VS", the Avi endpoint is shown, but the server_cloud is not shown in the dropdown:

I have opened a new Issue https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/issues/136
